export const questions = [
  {
    id: 0,
    question: "kind of animal 🧐",
    options: [
      "Dog 🐶",
      "Cat 😺",
      "Bird 🐦",
      "Exotic 🦄",
      "Rabbit 🐰",
      "Fish 🐠",
      "Hamster 🐹",
      "Turtle 🐢",
      "Fox 🦊",
      "Penguin 🐧",
    ],
  },
  {
    id: 1,
    question: "physical characteristic 🥷",
    options: [
      "Unusual eye color 👁️",
      "Striking fur/feather pattern 🌈",
      "Adorable expression 😊",
      "Magical element ✨",
      "Unique markings 🔮",
      "Iridescent scales/feathers 🌟",
      "Glowing aura 🌠",
      "Robotic parts 🤖",
      "Tiny wings 🧚",
      "Rainbow tail 🌈",
    ],
  },
  {
    id: 2,
    question: "A fancy accessory 🤹‍♂️",
    options: [
      "Fancy collar or bow tie 🎀",
      "Cute hat or headpiece 🎩",
      "Glasses or monocle 👓",
      "Flower crown or nature element 🌺",
      "Stylish bandana 🧣",
      "Shimmering jewelry 💎",
      "Superhero cape 🦸",
      "Wizard's wand 🪄",
      "Steampunk goggles 🥽",
      "Tiny backpack 🎒",
    ],
  },
  {
    id: 3,
    question: "the magical world ",
    options: [
      "Cozy home interior 🏠",
      "Lush nature scene 🌳",
      "Whimsical fantasy landscape 🏰",
      "Urban cityscape 🏙️",
      "Underwater wonderland 🌊",
      "Starry night sky 🌠",
      "Candy land 🍭",
      "Futuristic space station 🚀",
      "Ancient ruins 🏛️",
      "Volcanic landscape 🌋",
    ],
  },
  {
    id: 4,
    question: "Personality 🤩",
    options: [
      "Happy and playful 😄",
      "Regal and proud 👑",
      "Mysterious and alluring 🔮",
      "Relaxed and content 😌",
      "Curious and inquisitive 🧐",
      "Brave and adventurous 🦸",
      "Shy and sweet 🥺",
      "Mischievous and clever 😏",
      "Zen and wise 🧘",
      "Energetic and sporty 🏃",
    ],
  },
  {
    id: 5,
    question: "Lighting 🔦",
    options: [
      "Daytime ☀️",
      "Sunset 🌅",
      "Night 🌙",
      "Dawn 🌄",
      "Stormy weather ⛈️",
      "Rainbow sky 🌈",
      "Aurora borealis 🌌",
      "Eclipse 🌚",
      "Foggy mist 🌫️",
      "Shooting stars 🌠",
    ],
  },
  {
    id: 6,
    question: "Season 🥶",
    options: [
      "Spring bloom 🌸",
      "Summer heat 🌞",
      "Autumn leaves 🍂",
      "Winter snow ❄️",
      "Cherry blossom season 🌸",
      "Monsoon rains 🌧️",
      "Desert sandstorm 🏜️",
      "Tropical paradise 🏝️",
      "Arctic tundra 🧊",
      "Jungle humidity 🌴",
    ],
  },
  {
    id: 7,
    question: "Magic Element 🪄",
    options: [
      "Magic potion 🧪",
      "Ancient scroll 📜",
      "Crystal ball 🔮",
      "Flying carpet 🧞",
      "Enchanted mirror 🪞",
      "Time-turner ⏳",
      "Magical seeds 🌱",
      "Invisibility cloak 👻",
      "Fairy dust ✨",
      "Dragon egg 🥚",
    ],
  },
  {
    id: 8,
    question: "Style 😎",
    options: [
      "Pixel art style 👾",
      "Watercolor effect 🎨",
      "Comic book style 💥",
      "Neon glow 🌈",
      "Minimalist design ⬜",
      "Impressionist painting 🖼️",
      "3D rendered 🧊",
      "Retro 80s vibe 📼",
      "Anime inspired 🇯🇵",
      "Photorealistic 📸",
    ],
  },
  {
    id: 9,
    question: "Activity 🏃‍♂️",
    options: [
      "Playing an instrument 🎸",
      "Doing yoga 🧘",
      "Cooking 👨‍🍳",
      "Reading a book 📚",
      "Painting 🎨",
      "Gardening 🌱",
      "Stargazing 🔭",
      "Surfing 🏄",
      "Meditating 🧘‍♀️",
      "Dancing 💃",
    ],
  },
]

export const BreedNFT = "0x0d6181BabDeA5D3A2546636Ed8672a21D954d181"
export const BreedTopic =
  "0xddf1e8fec06a50aa72b8a39a06787808c53eca73b2bd1cc995681cf7b8014650"
export const DalleNFT = "0x4440b5eBEBac3DC6C4d4Eca62520ef783067EdDf"
